openapi: 3.0.1
info:
  contact:
    email: hello@mainnet.cash
  description: |
    A developer friendly bitcoin cash wallet api

    This API is currently in active development, breaking changes may
    be made prior to official release of version 1.

    **Important:** This library is in active development
  license:
    name: MIT Licence
    url: https://github.com/mainnet-cash/mainnet-js/blob/master/LICENSE
  termsOfService: https://mainnet.cash/terms/
  title: Mainnet Cash
  version: 0.1.7
externalDocs:
  description: Find out more about mainnet-js
  url: https://mainnet.cash
servers:
- description: unstable service (for development)
  url: https://rest-unstable.mainnet.cash/
- description: local development server via `yarn api:serve`
  url: http://localhost:3000/
tags:
- description: Interact with contracts
  externalDocs:
    description: Find out more
    url: https://rest-unstable.mainnet.cash/api-docs/#/contract/
  name: contract
- description: Mine regtest coins
  externalDocs:
    description: Find out more
    url: https://rest-unstable.mainnet.cash/api-docs/#/mine/
  name: mine
- description: Stateless convenience utilities
  externalDocs:
    description: Find out more
    url: https://rest-unstable.mainnet.cash/api-docs/#/util/
  name: util
- description: Interact with wallets
  externalDocs:
    description: Find out more
    url: https://rest-unstable.mainnet.cash/api-docs/#/wallet/
  name: wallet
- description: Create webhooks
  externalDocs:
    description: Find out more
    url: https://rest-unstable.mainnet.cash/api-docs/#/webhook/
  name: webhook
paths:
  /webhook/watch_address:
    post:
      operationId: watchAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchAddressRequest'
        description: |
          Based on the 'type' parameter the webhook will be triggered to either post balance or raw transactions to the 'url' -
          'transaction:in' for incoming only, 'transaction:out' for outgoing only and 'transaction:in,out' both for incoming and outgoing transactions.
          'balance' will post the object according to 'BalanceResponse' schema
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchAddressResponse'
          description: Successful operation
        "405":
          content: {}
          description: Invalid input
      summary: |
        Create a webhook to watch cashaddress balance and transactions.
      tags:
      - webhook
      x-eov-operation-handler: controllers/WebhookController
  /contract/escrow/create:
    post:
      operationId: createEscrow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EscrowRequest'
        description: Request a new escrow contract
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractResponse'
          description: successful operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Create an escrow contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /contract/escrow/utxos:
    post:
      description: |
        Returns all UTXOs that can be spent by the
        contract. Both confirmed and unconfirmed UTXOs are included.
      operationId: escrowUtxos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contract'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtxoResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: List specific utxos in a contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /contract/escrow/call:
    post:
      operationId: escrowFn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractFnRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
              - contractId: escrow:bchreg:qrc3vd0guh7mn9c9vl58rx6wcv92ld57aquqrre62e:bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0:bchreg:qznjmr5de89zv850lta6jeg5a6ftps4lyu58j8qcp8
              - walletId: wif:regtest:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
              - action: spend
              schema:
                $ref: '#/components/schemas/ContractFnResponse'
          description: successful operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Finalize an escrow contract
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /mine:
    post:
      operationId: mine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MineRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  description: a list of block hashes
                  type: string
                type: array
          description: request accepted
        "400":
          content: {}
          description: Invalid Request
      summary: Mine regtest coins to a specified address
      tags:
      - mine
      x-eov-operation-handler: controllers/MineController
  /util/convert:
    post:
      operationId: convert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertRequest'
      responses:
        "200":
          content:
            text/plain:
              schema:
                description: If a unit of account is passed, a plain number is returned.
                type: number
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: create a new wallet
      tags:
      - util
      x-eov-operation-handler: controllers/UtilController
  /wallet/create:
    post:
      operationId: createWallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletRequest'
        description: Request a new new random wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: create a new wallet
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/balance:
    post:
      operationId: balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceRequest'
        description: |
          Request for a wallet balance
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
            text/plain:
              schema:
                description: If a unit of account is passed, a plain number is returned.
                type: number
          description: successful operation
      summary: Get total balance for wallet
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/deposit_address:
    post:
      operationId: depositAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit address given a wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepositAddressResponse'
          description: successful operation
      summary: Get a deposit address in cash address format
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/deposit_qr:
    post:
      operationId: depositQr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit cash address as a Quick Response code (qrcode)
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScalableVectorGraphic'
          description: |
            A Qr code image data encoded string in the src field suitable for inclusion in html using:
               - \<img src\=\"{response.src}"\>
      summary: Get receiving cash address as a qrcode
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/info:
    post:
      operationId: info
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          The wallet to request information about, in serialized form.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletInfo'
          description: |
            Information about the wallet network, type, and keys
      summary: Get information about a wallet
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/max_amount_to_send:
    post:
      operationId: maxAmountToSend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaxAmountToSendRequest'
        description: get amount that will be spend with a spend max request. If a
          unit type is specified, a numeric value will be returned.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Get maximum spendable amount
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/utxo:
    post:
      operationId: utxos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request detailed list of unspent transaction outputs
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtxoResponse'
          description: successful operation
      summary: Get detailed information about unspent outputs (utxos)
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/send:
    post:
      operationId: send
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
        description: place a send request
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Send some amount to a given address
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
  /wallet/send_max:
    post:
      operationId: sendMax
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMaxRequest'
        description: Request to all available funds to a given address
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMaxResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
      summary: Send all available funds to a given address
      tags:
      - wallet
      x-eov-operation-handler: controllers/WalletController
components:
  schemas:
    Utxo:
      allOf:
      - $ref: '#/components/schemas/UnitType'
      example:
        utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
        index: 0.8008281904610115
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
        value: 100
      properties:
        index:
          type: number
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        value:
          example: 100
          type: number
        utxoId:
          description: serialized outpoint
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          type: string
      required:
      - amount
      - txId
      - utxoId
    BalanceRequest:
      allOf:
      - $ref: '#/components/schemas/UnitType'
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
      required:
      - walletId
    BalanceResponse:
      example:
        bch: 1
        sat: 100000000
        usd: 438.02
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 1
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 100000000
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 438.02
          type: number
    Error:
      properties:
        message:
          type: string
        stack:
          type: string
    WatchAddressRequest:
      example:
        recurrence: recurrent
        cashaddr: bchtest:qzd0tv75gx6y0zspzwqpgkwkq0n72g8fsq2zch26s2
        type: transaction:in,out
        url: http://example.com/webhook
        duration_sec: 86400
      properties:
        cashaddr:
          description: |
            Cash address to watch
          example: bchtest:qzd0tv75gx6y0zspzwqpgkwkq0n72g8fsq2zch26s2
          type: string
        url:
          description: Url to be called when configured action is triggered
          example: http://example.com/webhook
          type: string
        type:
          default: transaction:in,out
          description: Type of watch operation
          enum:
          - transaction:in
          - transaction:out
          - transaction:in,out
          - balance
          example: transaction:in,out
          type: string
        recurrence:
          default: once
          description: Action recurrence. Indicates if webhook should be triggered
            recurrently until expire or only once
          enum:
          - once
          - recurrent
          example: recurrent
          type: string
        duration_sec:
          default: 86400
          description: Duration of the webhook lifetime in seconds before it will
            expire.
          example: 86400
          type: number
      required:
      - cashaddr
      - type
      - url
    WatchAddressResponse:
      example:
        id: 1
      properties:
        id:
          description: Webhook Id created in the system
          example: 1
          format: integer
          type: number
    ZeroBalanceResponse:
      example:
        bch: 0
        sat: 0
        usd: 0
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 0
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 0
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 0
          type: number
    Contract:
      example:
        contractId: contractId
      properties:
        contractId:
          description: |
            serialized contract
          type: string
      required:
      - contractId
    EscrowRequest:
      example:
        arbiterAddr: bchtest:qzspcywxmm4fqhf9kjrknrc3grsv2vukeqyjqla0nt
        amount: 10000
        buyerAddr: bchtest:qrnluuge56ahxsy6pplq43rva7k6s9dknu4p5278ah
        sellerAddr: bchtest:qz00pk9lfs0k9f5vf3j8h66qfmqagk8nc56elq4dv2
        nonce: 808
      properties:
        buyerAddr:
          description: The cashaddress of the buyer
          example: bchtest:qrnluuge56ahxsy6pplq43rva7k6s9dknu4p5278ah
        arbiterAddr:
          description: The cashaddress of the arbiter
          example: bchtest:qzspcywxmm4fqhf9kjrknrc3grsv2vukeqyjqla0nt
        sellerAddr:
          description: The cashaddress of the seller
          example: bchtest:qz00pk9lfs0k9f5vf3j8h66qfmqagk8nc56elq4dv2
        amount:
          description: Numeric amount to be transferred by the contract in satoshi,
            amount must be less than 21 BCH.
          example: 10000
          type: number
        nonce:
          description: A unique value added to the contract, which allows the contract
            to be different from an otherwise identical contract, i.e. two monthly
            orders.
          example: 808
          type: number
      required:
      - amount
      - arbiterAddr
      - buyerAddr
      - sellerAddr
    ContractResponse:
      example:
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        contractId: contractId
      properties:
        contractId:
          description: |
            serialized contract
          type: string
        cashaddr:
          description: The funding address for the contract
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
    ContractFnRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        contractId: contractId
        action: spend
        to: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        utxoIds:
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0:1000
        - 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0:1000
        nonce: 808
        getHexOnly: true
      properties:
        contractId:
          description: |
            serialized contract
          type: string
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        action:
          description: Action for finalization of contract.
          enum:
          - spend
          - refund
          example: spend
          type: string
        to:
          description: output for the transaction
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        getHexOnly:
          description: |
            getHexOnly (default:false), if true, will cause only the transaction hex to be returned; if false, the transaction will be sent to the network
          type: boolean
        utxoIds:
          items:
            description: The hash of a transaction and index of the utxo and amount
              in satoshi
            example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0:1000
            type: string
          type: array
        nonce:
          description: A unique value added to the contract, which allows the contract
            to be different from an otherwise identical contract, i.e. two monthly
            orders.
          example: 808
          type: number
      required:
      - action
      - contractId
      - walletId
    ContractFnResponse:
      example:
        contractId: contractId
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
        hex: 0200000001f6d804c0a2f33936dd8b535d1... bdf0e43b30135be5251
      properties:
        contractId:
          description: |
            serialized contract
          type: string
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        hex:
          description: The transaction as bitcoin encoded hex
          example: 0200000001f6d804c0a2f33936dd8b535d1... bdf0e43b30135be5251
          type: string
    ScalableVectorGraphic:
      example:
        src: data:image/svg+xml;base64,PD94bWwgdm... ==**
        alt: A Bitcoin Cash Qr Code
        title: bitcoincash:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      properties:
        src:
          description: |
            A Qr code image data in svg format as utf-8 encoded string.
            Suitable for inclusion in html using:
                - \<img src\=\"**data:image/svg+xml;base64,PD94bWwgdm... ==**"\>
          example: data:image/svg+xml;base64,PD94bWwgdm... ==**
          type: string
        title:
          description: hover text for graphic
          example: bitcoincash:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        alt:
          description: assistive text
          example: A Bitcoin Cash Qr Code
          type: string
    SendMaxRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        cashaddr:
          example: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          type: string
      required:
      - cashaddr
      - walletId
    MaxAmountToSendRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        output_count: 0
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        output_count:
          description: |
            (optional) if sending all funds to multiple addresses, the
            count of the number of address funds will be sent
            to may be included.
          format: int32
          type: integer
      required:
      - walletId
    SerializedWallet:
      discriminator:
        propertyName: walletId
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
      required:
      - walletId
    DepositAddressResponse:
      example:
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      properties:
        cashaddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
    UtxoResponse:
      example:
        utxos:
        - utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          index: 0.8008281904610115
          txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          value: 100
        - utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          index: 0.8008281904610115
          txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          value: 100
      properties:
        utxos:
          items:
            $ref: '#/components/schemas/Utxo'
          type: array
    WalletResponse:
      allOf:
      - $ref: '#/components/schemas/NetworkEnum'
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        wif: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        name: username1
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        wif:
          description: |
            The wallet in Wallet Import Format (WIF)
          example: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        name:
          description: User defined string for wallet
          example: username1
          type: string
        cashaddr:
          description: |
            The address in cashaddr format.
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
      type: object
    MineRequest:
      example:
        cashaddr: bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        blocks: 105
      properties:
        cashaddr:
          example: bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        blocks:
          description: the number of blocks to mine
          example: 105
          type: number
    ConvertRequest:
      example:
        from: BCH
        to: USD
        value: 100
      properties:
        value:
          example: 100
          type: number
        from:
          description: Provided value unit of account.
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: BCH
          type: string
        to:
          description: Unit of account to be returned
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: USD
          type: string
    WalletRequest:
      allOf:
      - $ref: '#/components/schemas/NetworkEnum'
      - $ref: '#/components/schemas/WalletType'
      example:
        type: wif
        network: testnet
        name: username1
      properties:
        name:
          description: User defined string for wallet
          example: username1
          type: string
      type: object
    SendRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        to:
        - cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          value: 100
        - cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          value: 100
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        to:
          items:
            $ref: '#/components/schemas/SendRequestItem'
          type: array
      type: object
    SendRequestItem:
      allOf:
      - $ref: '#/components/schemas/UnitType'
      example:
        cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
        value: 100
      properties:
        cashaddr:
          example: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          type: string
        value:
          example: 100
          type: number
      required:
      - cashaddr
      - unit
      - value
      type: object
    SendMaxResponse:
      example:
        balance:
          bch: 0
          sat: 0
          usd: 0
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
      properties:
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        balance:
          $ref: '#/components/schemas/ZeroBalanceResponse'
      type: object
    SendResponse:
      example:
        balance:
          bch: 1
          sat: 100000000
          usd: 438.02
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
      properties:
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        balance:
          $ref: '#/components/schemas/BalanceResponse'
      type: object
    NetworkEnum:
      discriminator:
        propertyName: network
      properties:
        network:
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          example: testnet
          type: string
    UnitType:
      discriminator:
        propertyName: unit_type
      properties:
        unit:
          description: Unit of account.
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: sat
          type: string
    WalletType:
      discriminator:
        propertyName: wallet_type
      properties:
        type:
          description: Wallet type, either a mnemonic seed single address wallet,
            a simple private key (wif) or a Hierarchical Deterministic wallet determined
            from a seed.
          enum:
          - wif
          - hd
          - seed
          example: seed
          type: string
    WalletInfo:
      allOf:
      - $ref: '#/components/schemas/NetworkEnum'
      example:
        cashaddr: cashaddr
        privateKey: privateKey
        walletId: walletId
        walletDbEntry: walletDbEntry
        seed:
          seed: seed
          derivationPath: derivationPath
        name: name
        isTestnet: true
        publicKey: publicKey
        privateKeyWif: privateKeyWif
        publicKeyHash: publicKeyHash
      properties:
        cashaddr:
          type: string
        isTestnet:
          type: boolean
        name:
          type: string
        publicKey:
          type: string
        publicKeyHash:
          type: string
        privateKey:
          type: string
        privateKeyWif:
          type: string
        seed:
          $ref: '#/components/schemas/WalletMnemonic'
        walletId:
          type: string
        walletDbEntry:
          type: string
    WalletMnemonic:
      discriminator:
        propertyName: seed
      example:
        seed: seed
        derivationPath: derivationPath
      properties:
        seed:
          type: string
        derivationPath:
          type: string
